[package]
name = "delta-lake-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
deltalake = { version = "0.29.1", features = ["datafusion"] }
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"] }
url = "2.5.7"
serde_json = "1"
datafusion = "50"
